apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: default
spec:
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80